apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.2.4
  bindPort: 6443
nodeRegistration:
  name: k8s-master-1
  criSocket: unix:///var/run/containerd/containerd.sock

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "135.235.144.80:6443"
apiServer:
  certSANs:
    - k8s.ridhampatel.me
    - k8s-master-1
    - k8s-master-2
    - 127.0.0.1
    - localhost
    - 192.168.2.4
    - 192.168.2.5

etcd:
  external:
    endpoints:
      - https://192.168.1.4:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/etcd/client.crt
    keyFile: /etc/kubernetes/pki/etcd/client.key

networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
